import React from "react";

const LAST_UPDATED = "November 11, 2025";
const COMPANY_NAME = "Archetype Original, LLC (d/b/a Plan2Tasks)";
const ADDRESS = "2104 Pearl St, Carthage, MO 64836";
const CONTACT_EMAIL = "bart@archetypeoriginal.com";

export function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#F5F3F0] px-6 py-16">
      <div className="max-w-5xl mx-auto bg-white border border-stone-200 rounded-3xl shadow-sm p-12 space-y-6">
        <header className="space-y-2 text-center">
          <h1 className="text-4xl font-bold text-stone-900">Privacy Policy</h1>
          <p className="text-sm uppercase tracking-wide text-stone-500">
            Last updated: {LAST_UPDATED}
          </p>
        </header>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">1. Introduction</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            Welcome to Plan2Tasks (“we”, “our” or “us”). We respect your privacy and are committed to
            protecting your personal information. This Privacy Policy explains how we collect, use,
            disclose, and safeguard your information when you use our website, mobile application and
            software-as-a-service platform (collectively, the “Service”). By accessing or using the
            Service, you agree to the collection and use of information in accordance with this Privacy
            Policy.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">2. Definitions</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            <strong>“Personal Data”</strong> means any information that relates to an identified or
            identifiable individual.
          </p>
          <p className="text-base text-stone-600 leading-relaxed">
            <strong>“Usage Data”</strong> means data collected automatically, either generated by your
            use of the Service or from the infrastructure of the Service (e.g., IP address, browser
            type).
          </p>
          <p className="text-base text-stone-600 leading-relaxed">
            <strong>“Service”</strong> refers to Plan2Tasks and any features, functionalities, related
            websites, mobile apps or integrations.
          </p>
          <p className="text-base text-stone-600 leading-relaxed">
            <strong>“You”</strong> means the individual using the Service or the company or entity on
            behalf of which such individual uses the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">3. Information We Collect</h2>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold text-stone-900">3.1 Personal Data you provide</h3>
            <p className="text-base text-stone-600 leading-relaxed">
              When you register for an account, subscribe, or otherwise use the Service, we may ask you
              to provide certain Personal Data, such as:
            </p>
            <ul className="list-disc list-inside text-base text-stone-600 leading-relaxed space-y-1">
              <li>Name</li>
              <li>Email address</li>
              <li>Company (if applicable)</li>
              <li>Billing / payment details (if you purchase a subscription)</li>
              <li>Other information you choose to provide (such as profile data)</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold text-stone-900">3.2 Usage Data and Automatic Collection</h3>
            <p className="text-base text-stone-600 leading-relaxed">
              We may collect Usage Data automatically when you use the Service, including but not limited
              to:
            </p>
            <ul className="list-disc list-inside text-base text-stone-600 leading-relaxed space-y-1">
              <li>IP address</li>
              <li>Device information (type, operating system)</li>
              <li>Browser type and version</li>
              <li>Pages or features visited or used</li>
              <li>Time and date of access</li>
              <li>Referring / exit pages</li>
              <li>Cookies and similar tracking technologies</li>
            </ul>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">4. Use of Your Information</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We use the information we collect for purposes such as:
          </p>
          <ul className="list-disc list-inside text-base text-stone-600 leading-relaxed space-y-1">
            <li>Providing, maintaining and improving the Service</li>
            <li>Managing your account and subscription</li>
            <li>Communicating with you (e.g., updates, notifications, support)</li>
            <li>Personalising or tailoring your experience</li>
            <li>Running analytics and business intelligence to understand usage</li>
            <li>Complying with legal obligations</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">5. Disclosure of Your Information</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We may share your information as follows:
          </p>
          <ul className="list-disc list-inside text-base text-stone-600 leading-relaxed space-y-1">
            <li>
              With service providers and third-party vendors who assist us in operating the Service (e.g.,
              payment processors, hosting providers)
            </li>
            <li>If required by law (e.g., to comply with a subpoena or similar legal process)</li>
            <li>
              If we believe disclosure is necessary to protect our rights, property or safety, or the
              rights, property or safety of others
            </li>
            <li>
              In connection with any merger, acquisition, financing, sale of assets or similar transaction
              (you will be notified)
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">6. Data Security</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We implement commercially reasonable technical and organisational measures to protect your
            Personal Data. However, no method of transmission over the Internet or method of electronic
            storage is 100% secure and we cannot guarantee absolute security.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">7. Data Retention</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We will retain your Personal Data only for as long as necessary for the purposes set out in
            this Privacy Policy, and in accordance with legal or regulatory obligations. Usage Data may be
            retained for internal analysis for a shorter or longer period depending on our ongoing needs.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">8. International Transfers</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            Your information may be transferred to — and processed in — locations outside your state,
            province, country or other governmental jurisdiction where data protection laws may differ. By
            submitting your information, you consent to such transfers. We will take steps reasonably
            necessary to ensure your data is protected.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">9. Cookies and Tracking Technologies</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We and our service providers use cookies, web beacons, tags and other similar technologies to
            collect and track information about your usage of the Service, measure and analyse aggregate
            usage, and improve the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">10. Children’s Privacy</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            Our Service is not intended for children under the age of 13 (or minimum age required by local
            law). We do not knowingly collect Personal Data from children under that age. If we become
            aware that we have collected Personal Data from a child under the applicable age without
            parental consent, we will take steps to remove that information.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">11. Your Rights</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            Depending on your jurisdiction, you may have rights such as:
          </p>
          <ul className="list-disc list-inside text-base text-stone-600 leading-relaxed space-y-1">
            <li>The right to access your Personal Data</li>
            <li>The right to correct or update your Personal Data</li>
            <li>The right to delete your Personal Data</li>
            <li>The right to restrict or object to certain processing</li>
          </ul>
          <p className="text-base text-stone-600 leading-relaxed">
            If you would like to exercise your rights, contact us at {CONTACT_EMAIL}.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">12. Changes to this Privacy Policy</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            We may update this Privacy Policy from time to time. We will notify you of changes by posting
            the new version on our Service and updating the “Last updated” date. Your continued use of the
            Service after the update constitutes your acceptance of the revised version.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold text-stone-900">13. Contact Us</h2>
          <p className="text-base text-stone-600 leading-relaxed">
            If you have any questions about this Privacy Policy, please contact us at:
          </p>
          <p className="text-base text-stone-600 leading-relaxed">
            {COMPANY_NAME}
            <br />
            {ADDRESS}
            <br />
            Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-stone-900 hover:underline">{CONTACT_EMAIL}</a>
          </p>
        </section>
      </div>
    </main>
  );
}
import React from "react";

